"""SQLAlchemy models for the Device Inventory & Network Ops module.

All models extend the shared ``Base`` from ``database.models`` so they are
created by the same ``create_tables()`` call.
"""

from __future__ import annotations

import uuid
from datetime import datetime, timezone

from sqlalchemy import (
    JSON,
    Boolean,
    Column,
    DateTime,
    ForeignKey,
    Integer,
    String,
    Text,
)

from database.models import Base


# ---------------------------------------------------------------------------
# Helper
# ---------------------------------------------------------------------------
def _uuid() -> str:
    return str(uuid.uuid4())


def _utcnow() -> datetime:
    return datetime.now(tz=timezone.utc)


# ---------------------------------------------------------------------------
# Authorized Network
# ---------------------------------------------------------------------------
class AuthorizedNetwork(Base):
    """A network the user owns/administers with explicit consent."""

    __tablename__ = "inv_authorized_networks"

    id = Column(String, primary_key=True, default=_uuid)
    workspace_id = Column(String, nullable=False, index=True)
    name = Column(String(255), nullable=False)
    site = Column(String(255))
    router_type = Column(String(50), nullable=False, default="manual")  # manual | unifi | mikrotik | fritzbox | openwrt
    config_ref = Column(String(512))  # server-side secret ref (never sent to client)
    capabilities = Column(JSON, default=dict)
    consent_at = Column(DateTime, nullable=False)
    consent_text_version = Column(String(32), nullable=False, default="1.0")
    consent_actor_user_id = Column(String, nullable=False)
    created_at = Column(DateTime, default=_utcnow)
    updated_at = Column(DateTime, default=_utcnow, onupdate=_utcnow)
    is_deleted = Column(Boolean, default=False)


# ---------------------------------------------------------------------------
# Device
# ---------------------------------------------------------------------------
class Device(Base):
    """A device observed on an authorized network."""

    __tablename__ = "inv_devices"

    id = Column(String, primary_key=True, default=_uuid)
    workspace_id = Column(String, nullable=False, index=True)
    network_id = Column(String, ForeignKey("inv_authorized_networks.id"), nullable=False, index=True)
    device_key = Column(String(128), nullable=False, index=True)  # HMAC(mac, secret) — stable fingerprint
    label = Column(String(255))
    tags = Column(JSON, default=list)
    category = Column(String(50), default="unknown")  # laptop | phone | tablet | iot | server | printer | unknown
    owner = Column(String(255))
    criticality = Column(String(10), default="low")  # low | med | high
    approved = Column(Boolean, default=False)
    risk_score = Column(Integer, default=0)  # 0-100
    risk_level = Column(String(10), default="low")  # low | med | high
    status = Column(String(20), default="active")  # active | inactive | quarantined | logical
    notes = Column(Text)
    attachments = Column(JSON, default=list)
    first_seen_at = Column(DateTime, default=_utcnow)
    last_seen_at = Column(DateTime, default=_utcnow)
    created_at = Column(DateTime, default=_utcnow)
    updated_at = Column(DateTime, default=_utcnow, onupdate=_utcnow)


# ---------------------------------------------------------------------------
# Observation (append-only timeline)
# ---------------------------------------------------------------------------
class Observation(Base):
    """Immutable record of a device sighting on the network."""

    __tablename__ = "inv_observations"

    id = Column(String, primary_key=True, default=_uuid)
    device_id = Column(String, ForeignKey("inv_devices.id"), nullable=False, index=True)
    network_id = Column(String, ForeignKey("inv_authorized_networks.id"), nullable=False, index=True)
    source = Column(String(50), nullable=False, default="manual")  # manual | adapter
    connection_type = Column(String(50))  # wifi | ethernet | unknown
    first_seen_at = Column(DateTime, default=_utcnow)
    last_seen_at = Column(DateTime, default=_utcnow)
    seen_count = Column(Integer, default=1)
    ip_masked = Column(String(50))  # e.g. 192.168.1.***
    mac_masked = Column(String(50))  # e.g. AA:BB:CC:**:**:**
    vendor = Column(String(255))
    hostname = Column(String(255))
    metadata_json = Column("metadata", JSON, default=dict)
    created_at = Column(DateTime, default=_utcnow)


# ---------------------------------------------------------------------------
# Alert
# ---------------------------------------------------------------------------
class Alert(Base):
    """Security/ops alert generated by the diff/policy engine."""

    __tablename__ = "inv_alerts"

    id = Column(String, primary_key=True, default=_uuid)
    workspace_id = Column(String, nullable=False, index=True)
    network_id = Column(String, ForeignKey("inv_authorized_networks.id"), nullable=False, index=True)
    device_id = Column(String, ForeignKey("inv_devices.id"), index=True)
    type = Column(
        String(50), nullable=False
    )  # new_device | unapproved_device | odd_hours | long_absent | policy_violation
    severity = Column(String(10), nullable=False, default="info")  # info | low | med | high
    status = Column(String(20), nullable=False, default="open")  # open | ack | resolved
    created_at = Column(DateTime, default=_utcnow)
    ack_at = Column(DateTime)
    resolved_at = Column(DateTime)
    payload = Column(JSON, default=dict)
    dedup_key = Column(String(255), index=True)


# ---------------------------------------------------------------------------
# PolicyRule
# ---------------------------------------------------------------------------
class PolicyRule(Base):
    """User-defined or built-in policy rule that triggers alerts."""

    __tablename__ = "inv_policy_rules"

    id = Column(String, primary_key=True, default=_uuid)
    workspace_id = Column(String, nullable=False, index=True)
    network_id = Column(String, ForeignKey("inv_authorized_networks.id"))
    name = Column(String(255), nullable=False)
    enabled = Column(Boolean, default=True)
    conditions = Column(JSON, nullable=False, default=dict)
    actions = Column(JSON, nullable=False, default=dict)
    severity = Column(String(10), default="med")
    schedule = Column(String(100))  # cron expression or null
    created_by = Column(String)
    created_at = Column(DateTime, default=_utcnow)
    updated_at = Column(DateTime, default=_utcnow, onupdate=_utcnow)


# ---------------------------------------------------------------------------
# Integration
# ---------------------------------------------------------------------------
class Integration(Base):
    """Notification integration (email, webhook, Slack, etc.)."""

    __tablename__ = "inv_integrations"

    id = Column(String, primary_key=True, default=_uuid)
    workspace_id = Column(String, nullable=False, index=True)
    type = Column(String(50), nullable=False)  # email | webhook | slack | discord | teams
    config_ref = Column(String(512))  # server-side only
    enabled = Column(Boolean, default=True)
    severity_filter = Column(JSON, default=list)  # e.g. ["high", "med"]
    created_at = Column(DateTime, default=_utcnow)
    updated_at = Column(DateTime, default=_utcnow, onupdate=_utcnow)


# ---------------------------------------------------------------------------
# MaintenanceWindow
# ---------------------------------------------------------------------------
class MaintenanceWindow(Base):
    """Planned downtime window that suppresses selected alert types."""

    __tablename__ = "inv_maintenance_windows"

    id = Column(String, primary_key=True, default=_uuid)
    workspace_id = Column(String, nullable=False, index=True)
    network_id = Column(String, ForeignKey("inv_authorized_networks.id"))
    start_at = Column(DateTime, nullable=False)
    end_at = Column(DateTime, nullable=False)
    suppress_alert_types = Column(JSON, default=list)  # e.g. ["new_device", "unapproved_device"]
    reason = Column(Text)
    created_by = Column(String)
    created_at = Column(DateTime, default=_utcnow)


# ---------------------------------------------------------------------------
# InventoryAuditLog (separate from core AuditLog for module isolation)
# ---------------------------------------------------------------------------
class InventoryAuditLog(Base):
    """Audit log specific to inventory operations."""

    __tablename__ = "inv_audit_logs"

    id = Column(String, primary_key=True, default=_uuid)
    workspace_id = Column(String, nullable=False, index=True)
    actor_user_id = Column(String, nullable=False)
    action = Column(String(100), nullable=False)
    entity_type = Column(String(50), nullable=False)
    entity_id = Column(String)
    timestamp = Column(DateTime, default=_utcnow, index=True)
    ip_address = Column(String(50))
    user_agent = Column(String(512))
    metadata_json = Column("metadata", JSON, default=dict)


# ---------------------------------------------------------------------------
# Consent text versions
# ---------------------------------------------------------------------------
CONSENT_TEXT_V1 = (
    "I confirm that I own or have explicit written authorization to manage "
    "this network and all devices connected to it. I understand that this system "
    "will ONLY read device information from my network's official management "
    "interface or imported data files. No scanning, probing, or unauthorized "
    "network access will be performed."
)

CONSENT_VERSIONS: dict[str, str] = {
    "1.0": CONSENT_TEXT_V1,
}
