name: HackGPT
options:
  bundleIdPrefix: com.hackgpt
  deploymentTarget:
    iOS: "16.0"
    macOS: "13.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic
    MARKETING_VERSION: "2.0.0"
    CURRENT_PROJECT_VERSION: "1"

targets:
  HackGPT-macOS:
    type: application
    platform: macOS
    deploymentTarget: "13.0"
    sources:
      - path: Sources/HackGPTApp
        type: group
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.hackgpt.enterprise
        PRODUCT_NAME: HackGPT
        INFOPLIST_FILE: HackGPT.app/Contents/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/../Frameworks"
        MACOSX_DEPLOYMENT_TARGET: "13.0"
        CODE_SIGN_ENTITLEMENTS: ""
        ENABLE_HARDENED_RUNTIME: NO
    postBuildScripts:
      - script: |
          # Copy icon to Resources
          if [ -f "${SRCROOT}/HackGPT.app/Contents/Resources/AppIcon.icns" ]; then
            mkdir -p "${BUILT_PRODUCTS_DIR}/${PRODUCT_NAME}.app/Contents/Resources"
            cp "${SRCROOT}/HackGPT.app/Contents/Resources/AppIcon.icns" "${BUILT_PRODUCTS_DIR}/${PRODUCT_NAME}.app/Contents/Resources/"
          fi
        name: "Copy App Icon"

  HackGPT-iOS:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: Sources/HackGPTApp
        type: group
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.hackgpt.enterprise.ios
        PRODUCT_NAME: HackGPT
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        IPHONEOS_DEPLOYMENT_TARGET: "16.0"
        TARGETED_DEVICE_FAMILY: "1,2"
        SUPPORTS_MACCATALYST: NO
        SWIFT_EMIT_LOC_STRINGS: YES
        GENERATE_INFOPLIST_FILE: YES
        CODE_SIGN_IDENTITY: "Apple Development"
